{
 "title": "iot",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"number\")\n  |> filter(fn: (r) => r[\"host\"] == \"fazole\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "fazole/pump/pump${n}/state",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pump\")\n  |> filter(fn: (r) => r[\"host\"] == \"fazole\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"fazole\")\n  |> filter(fn: (r) => r[\"_field\"] == \"current_temperature\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"climate\")\n  |> filter(fn: (r) => r[\"component\"] == \"pump1_t\" or r[\"component\"] == \"pump2_t\" or r[\"component\"] == \"pump4_t\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "fazole",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"fazole\")\n  |> filter(fn: (r) => r[\"_field\"] == \"action\")\n  |> filter(fn: (r) => r[\"component\"] == \"pump2_t\" or r[\"component\"] == \"pump1_t\" or r[\"component\"] == \"pump4_t\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "teploticky",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 19, "x": 5, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"air\" or r[\"_field\"] == \"living_room_temperature\" or r[\"_field\"] == \"onboard_temp_1\" or r[\"_field\"] == \"onboard_temp_2\" or r[\"_field\"] == \"radiator\" or r[\"_field\"] == \"temp\" or r[\"_field\"] == \"temperature\" or r[\"_field\"] == \"venky\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}